# Generated by Django 6.0.6 on 2026-06-13 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stream',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stream',
            name='archived',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stream',
            name='cancelled',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stream',
            name='delivered',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stream',
            name='delivering',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stream',
            name='hold',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stream',
            name='new_order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stream',
            name='packing',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stream',
            name='returned',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stream',
            name='visit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stream',
            name='waiting',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
    ]
