# Generated by Django 6.0.6 on 2026-06-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_category_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='cancelled',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='delivering',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='hold',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='new_order',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='packing',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='returned',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='waiting',
        ),
    ]
