# Generated by Django 6.0.5 on 2026-06-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_remove_user_city_remove_user_region_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='photo',
            new_name='image',
        ),
    ]
