# Generated by Django 6.0.5 on 2026-06-11 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_rename_photo_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='stream',
            name='view_count',
        ),
        migrations.AddField(
            model_name='stream',
            name='archived',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stream',
            name='cancelled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stream',
            name='delivered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stream',
            name='delivering',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stream',
            name='hold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stream',
            name='new_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stream',
            name='packing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stream',
            name='returned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stream',
            name='visit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stream',
            name='waiting',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stream',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_streams', to=settings.AUTH_USER_MODEL),
        ),
    ]
