# Generated by Django 6.0.5 on 2026-06-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_district_remove_stream_view_count_stream_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
