# Generated by Django 6.0.5 on 2026-06-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_stream_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
